export const SONGS_ACTION_TYPES = {
  SET_IS_SONGS_PLAY: "SET_IS_SONGS_PLAY",
  SET_SONG_SELECTED: "SET_SONG_SELECTED",
  SET_IS_MENU_OPNE: "SET_IS_MENU_OPNE",
  SET_SONGS_TOTAL: "SET_SONGS_TOTAL",
};
