export const SONGS_ACTION_TYPES = {
  SET_IS_MENU_OPNE: "SET_IS_MENU_OPNE",
  SET_IS_ALBUM_OPNE: "SET_IS_ALBUM_OPNE",
  SET_IS_SONGS_PLAY: "SET_IS_SONGS_PLAY",
  SET_PLAY_SONG: "SET_PLAY_SONG",
  SET_CURRENT_ALBUM: "SET_CURRENT_ALBUM",
  SET_CURRENT_SONG: "SET_CURRENT_SONG",
  SET_ALBUM_SONGS: "SET_ALBUM_SONGS",
};
